include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/_archive/**
    - lib/generated_plugin_registrant.dart

linter:
  rules:
    - avoid_print: false  # Allow print for now
    - prefer_const_constructors: true
    - prefer_const_literals_to_create_immutables: true
