import '../models/post.dart';

class MockDataService {
  static List<Drill> _drills = [
    // Football Drills
    Drill(
      id: 'football_1',
      name: '40m Sprint',
      icon: '⚡',
      sport: 'Football',
      category: 'Sports',
      description: 'Test your acceleration and top speed over 40 meters.',
      instructions: [
        'Start from a standing position',
        'Sprint as fast as possible for 40 meters',
        'Focus on proper form and breathing'
      ],
      estimatedDuration: 10,
      difficulty: 'Medium',
    ),
    Drill(
      id: 'football_2',
      name: '100m Sprint',
      icon: '🏃',
      sport: 'Football',
      category: 'Sports',
      description: 'Full sprint endurance test over 100 meters.',
      instructions: [
        'Start from blocks or standing',
        'Maintain speed throughout the distance',
        'Work on pacing and recovery'
      ],
      estimatedDuration: 20,
      difficulty: 'Hard',
    ),
    Drill(
      id: 'football_3',
      name: 'Agility Ladder',
      icon: '🪜',
      sport: 'Football',
      category: 'Sports',
      description: 'Improve footwork and coordination with ladder drills.',
      instructions: [
        'Step through each rung quickly',
        'Alternate feet and patterns',
        'Focus on speed and precision'
      ],
      estimatedDuration: 15,
      difficulty: 'Easy',
    ),
    Drill(
      id: 'football_4',
      name: 'Ball Control',
      icon: '⚽',
      sport: 'Football',
      category: 'Sports',
      description: 'Practice dribbling and ball control skills.',
      instructions: [
        'Keep the ball close to your feet',
        'Use both feet alternately',
        'Practice in tight spaces'
      ],
      estimatedDuration: 20,
      difficulty: 'Medium',
    ),

    // Badminton Drills
    Drill(
      id: 'badminton_1',
      name: 'Footwork Drill',
      icon: '🏸',
      sport: 'Badminton',
      category: 'Sports',
      description: 'Improve court coverage and movement patterns.',
      instructions: [
        'Move to each corner of the court',
        'Practice split-step timing',
        'Focus on quick directional changes'
      ],
      estimatedDuration: 30,
      difficulty: 'Medium',
    ),
    Drill(
      id: 'badminton_2',
      name: 'Smash Practice',
      icon: '💥',
      sport: 'Badminton',
      category: 'Sports',
      description: 'Develop powerful overhead smashes.',
      instructions: [
        'Position yourself correctly',
        'Generate power from legs and core',
        'Follow through with the racket'
      ],
      estimatedDuration: 25,
      difficulty: 'Hard',
    ),
    Drill(
      id: 'badminton_3',
      name: 'Serve Accuracy',
      icon: '🎯',
      sport: 'Badminton',
      category: 'Sports',
      description: 'Perfect your serving technique and placement.',
      instructions: [
        'Stand behind the service line',
        'Aim for different service areas',
        'Practice both short and long serves'
      ],
      estimatedDuration: 20,
      difficulty: 'Easy',
    ),
    Drill(
      id: 'badminton_4',
      name: 'Drop Shot',
      icon: '🎾',
      sport: 'Badminton',
      category: 'Sports',
      description: 'Master deceptive drop shots near the net.',
      instructions: [
        'Approach the shuttle early',
        'Use wrist action for control',
        'Practice different angles'
      ],
      estimatedDuration: 25,
      difficulty: 'Medium',
    ),
  ];

  static List<Drill> getDrillsBySport(String sport) {
    return _drills.where((drill) => drill.sport == sport).toList();
  }

  static List<Post> getPosts() {
    return [
      Post(
        id: '1',
        userId: 'user1',
        userName: 'Sarah Johnson',
        userAvatar: 'https://i.pravatar.cc/150?img=1',
        userTier: 'Elite Athlete',
        content: 'Crushed my 40m sprint today! 🔥\nNew PR: 5.9s (-0.4s improvement)\nFeeling unstoppable! 💪',
        mediaUrl: 'placeholder',
        mediaThumbnail: null,
        mediaType: 'video',
        mediaDuration: 15,
        drillName: '40m Sprint',
        drillIcon: '⚡',
        score: 87,
        tier: 'ELITE',
        likes: 124,
        comments: 18,
        reposts: 0,
        shares: 3,
        likedBy: [],
        timestamp: DateTime.now().subtract(Duration(hours: 2)),
        isVerified: true,
      ),
      Post(
        id: '2',
        userId: 'user2',
        userName: 'Rajesh Kumar',
        userAvatar: 'https://i.pravatar.cc/150?img=2',
        userTier: 'Pro',
        content: 'Just unlocked the Speed Demon badge! 🏆\nConsistency is key. 6 weeks of training paying off! 😤',
        mediaUrl: null,
        mediaThumbnail: null,
        mediaType: 'none',
        mediaDuration: 0,
        drillName: 'Speed Demon Challenge',
        drillIcon: '🏃',
        score: 75,
        tier: 'PRO',
        likes: 89,
        comments: 12,
        reposts: 0,
        shares: 2,
        likedBy: [],
        timestamp: DateTime.now().subtract(Duration(hours: 5)),
        isVerified: false,
      ),
      Post(
        id: '3',
        userId: 'user3',
        userName: 'Priya Sharma',
        userAvatar: 'https://i.pravatar.cc/150?img=3',
        userTier: 'Advanced',
        content: 'Badminton shadow footwork drill complete! 🏸\nWorking on my court coverage. Tips welcome! 🙏',
        mediaUrl: 'placeholder',
        mediaThumbnail: null,
        mediaType: 'video',
        mediaDuration: 30,
        drillName: 'Badminton Footwork',
        drillIcon: '🏸',
        score: 82,
        tier: 'ADVANCED',
        likes: 67,
        comments: 24,
        reposts: 0,
        shares: 5,
        likedBy: [],
        timestamp: DateTime.now().subtract(Duration(hours: 8)),
        isVerified: false,
      ),
      Post(
        id: '4',
        userId: 'user4',
        userName: 'Michael Chen',
        userAvatar: 'https://i.pravatar.cc/150?img=4',
        userTier: 'Elite Athlete',
        content: 'New personal best in 100m! 10.8s 🏃‍♂️⚡\nAll that training finally paid off!',
        mediaUrl: 'placeholder',
        mediaThumbnail: null,
        mediaType: 'video',
        mediaDuration: 20,
        drillName: '100m Sprint',
        drillIcon: '⚡',
        score: 92,
        tier: 'ELITE',
        likes: 234,
        comments: 45,
        reposts: 0,
        shares: 12,
        likedBy: [],
        timestamp: DateTime.now().subtract(Duration(hours: 12)),
        isVerified: true,
      ),
      Post(
        id: '5',
        userId: 'user5',
        userName: 'Aisha Patel',
        userAvatar: 'https://i.pravatar.cc/150?img=5',
        userTier: 'Pro',
        content: 'Finished my first marathon today! 3:45:23 ⏱️\nFeeling accomplished but exhausted 😅',
        mediaUrl: null,
        mediaThumbnail: null,
        mediaType: 'none',
        mediaDuration: 0,
        drillName: 'Marathon',
        drillIcon: '🏃‍♀️',
        score: 78,
        tier: 'PRO',
        likes: 156,
        comments: 32,
        reposts: 0,
        shares: 8,
        likedBy: [],
        timestamp: DateTime.now().subtract(Duration(days: 1)),
        isVerified: false,
      ),
    ];
  }
}
