// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu5Nmi_eX1-6Efz-ET4or-u89ERhy65NQ',
    appId: '1:223564088435:web:39c48097bde2684bfc9606',
    messagingSenderId: '223564088435',
    projectId: 'khelify-3368e',
    authDomain: 'khelify-3368e.firebaseapp.com',
    storageBucket: 'khelify-3368e.firebasestorage.app',
    measurementId: 'G-24YK0THNSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBokCHU4k4MG6BhiW6iE2LAQ-jI7vhXVag',
    appId: '1:223564088435:android:4315de26e95b0fc1fc9606',
    messagingSenderId: '223564088435',
    projectId: 'khelify-3368e',
    storageBucket: 'khelify-3368e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx-6RCVu22U_CN6mVYasI9bseD__CLKUI',
    appId: '1:223564088435:ios:de5dfebf2a605eaefc9606',
    messagingSenderId: '223564088435',
    projectId: 'khelify-3368e',
    storageBucket: 'khelify-3368e.firebasestorage.app',
    iosClientId: '223564088435-7q3g34hclbkf7cidsv7c7naeivu7rm89.apps.googleusercontent.com',
    iosBundleId: 'com.example.khelifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx-6RCVu22U_CN6mVYasI9bseD__CLKUI',
    appId: '1:223564088435:ios:de5dfebf2a605eaefc9606',
    messagingSenderId: '223564088435',
    projectId: 'khelify-3368e',
    storageBucket: 'khelify-3368e.firebasestorage.app',
    iosClientId: '223564088435-7q3g34hclbkf7cidsv7c7naeivu7rm89.apps.googleusercontent.com',
    iosBundleId: 'com.example.khelifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu5Nmi_eX1-6Efz-ET4or-u89ERhy65NQ',
    appId: '1:223564088435:web:65840300f848ccb5fc9606',
    messagingSenderId: '223564088435',
    projectId: 'khelify-3368e',
    authDomain: 'khelify-3368e.firebaseapp.com',
    storageBucket: 'khelify-3368e.firebasestorage.app',
    measurementId: 'G-624S6H8JYX',
  );

}