import '../../features/drill/models/drill.dart';

/// All available drills in v1 of Khelify.
///
/// Sports: Football, Cricket, Athletics (active) + Boxing, Esports (coming soon).
/// Each ScoringCriterion includes biomechanical ideal angle ranges from
/// published sports science research for Gaussian falloff scoring.
class DrillConstants {
  static const List<String> activeSports = ['Football', 'Cricket', 'Athletics'];
  static const List<String> comingSoonSports = ['Boxing', 'Esports'];
  static List<String> get allSports => [...activeSports, ...comingSoonSports];

  static final List<Drill> allDrills = [
    // ═══════════════════════════════════════════════════════════════
    //  FOOTBALL
    // ═══════════════════════════════════════════════════════════════
    Drill(
      id: 'fb_sprint',
      name: 'Sprint Knee Drive',
      sport: 'Football',
      category: 'Speed',
      description: 'Full-speed sprint focusing on knee drive, arm swing, and forward lean.',
      instructions: [
        'Stand at the start line in a sprinter stance',
        'Sprint at maximum effort for 20-40 meters',
        'Focus on driving your knees high',
        'Maintain a forward lean during acceleration',
      ],
      estimatedDuration: Duration(seconds: 15),
      difficulty: 'intermediate',
      icon: '🏃',
      cameraPosition: 'side',
      scoringCriteria: [
        ScoringCriterion(
          name: 'Knee Drive',
          description: 'Hip-knee angle during stride (higher knee = better)',
          weight: 0.30,
          metricType: 'angle',
          idealMin: 70,  // Hip flexion at peak knee lift
          idealMax: 95,
          sigma: 12,
          landmarkA: 'leftHip',
          landmarkB: 'leftKnee',
          landmarkC: 'leftAnkle',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Forward Lean',
          description: 'Torso angle during acceleration phase',
          weight: 0.25,
          metricType: 'angle',
          idealMin: 155,  // Slight forward lean
          idealMax: 170,
          sigma: 10,
          landmarkA: 'leftKnee',
          landmarkB: 'leftHip',
          landmarkC: 'leftShoulder',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Arm Swing',
          description: 'Coordinated opposite arm-leg movement',
          weight: 0.25,
          metricType: 'form',
          idealMin: 60,  // Elbow angle during arm swing
          idealMax: 100,
          sigma: 15,
          landmarkA: 'leftShoulder',
          landmarkB: 'leftElbow',
          landmarkC: 'leftWrist',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Stride Consistency',
          description: 'Regularity of stride pattern',
          weight: 0.20,
          metricType: 'consistency',
          landmarkA: 'leftHip',
          landmarkB: 'leftKnee',
          landmarkC: 'leftAnkle',
          side: 'auto',
        ),
      ],
    ),
    Drill(
      id: 'fb_kick',
      name: 'Instep Kick',
      sport: 'Football',
      category: 'Technique',
      description: 'Instep kick technique for power and accuracy.',
      instructions: [
        'Place the ball on the ground',
        'Take a 3-step run-up at an angle',
        'Plant your support foot beside the ball',
        'Strike through the ball with your instep, follow through fully',
      ],
      estimatedDuration: Duration(seconds: 10),
      difficulty: 'intermediate',
      icon: '⚽',
      cameraPosition: 'side',
      scoringCriteria: [
        ScoringCriterion(
          name: 'Backswing',
          description: 'Knee flexion during backswing (kicking leg)',
          weight: 0.25,
          metricType: 'angle',
          idealMin: 40,  // Deep knee bend on backswing
          idealMax: 70,
          sigma: 12,
          landmarkA: 'leftHip',
          landmarkB: 'leftKnee',
          landmarkC: 'leftAnkle',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Contact Angle',
          description: 'Knee extension at ball contact',
          weight: 0.30,
          metricType: 'angle',
          idealMin: 150, // Near-full extension at contact
          idealMax: 175,
          sigma: 10,
          landmarkA: 'leftHip',
          landmarkB: 'leftKnee',
          landmarkC: 'leftAnkle',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Support Knee',
          description: 'Plant leg knee bend for stability',
          weight: 0.20,
          metricType: 'angle',
          idealMin: 155, // Slight bend, not locked
          idealMax: 170,
          sigma: 8,
          landmarkA: 'rightHip',
          landmarkB: 'rightKnee',
          landmarkC: 'rightAnkle',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Follow Through',
          description: 'Arm and body follow-through after kick',
          weight: 0.25,
          metricType: 'form',
        ),
      ],
    ),
    Drill(
      id: 'fb_cod',
      name: 'Change of Direction',
      sport: 'Football',
      category: 'Agility',
      description: 'Sharp direction change to test agility and balance.',
      instructions: [
        'Sprint towards a cone 5 meters away',
        'Plant your outside foot and cut sharply',
        'Accelerate in the new direction',
        'Keep your center of gravity low through the cut',
      ],
      estimatedDuration: Duration(seconds: 10),
      difficulty: 'advanced',
      icon: '⚡',
      cameraPosition: 'front',
      scoringCriteria: [
        ScoringCriterion(
          name: 'Plant Knee Flexion',
          description: 'Cutting leg knee bend during plant',
          weight: 0.30,
          metricType: 'angle',
          idealMin: 80,  // Deep knee bend on plant
          idealMax: 110,
          sigma: 12,
          landmarkA: 'leftHip',
          landmarkB: 'leftKnee',
          landmarkC: 'leftAnkle',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Hip Cut',
          description: 'Hip rotation angle during direction change',
          weight: 0.30,
          metricType: 'angle',
          idealMin: 130,
          idealMax: 160,
          sigma: 15,
          landmarkA: 'leftShoulder',
          landmarkB: 'leftHip',
          landmarkC: 'leftKnee',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Body Balance',
          description: 'Overall stability through the cut',
          weight: 0.20,
          metricType: 'form',
        ),
        ScoringCriterion(
          name: 'Recovery Speed',
          description: 'Quickness of acceleration after the cut',
          weight: 0.20,
          metricType: 'speed',
          landmarkB: 'leftAnkle',
        ),
      ],
    ),

    // ═══════════════════════════════════════════════════════════════
    //  CRICKET
    // ═══════════════════════════════════════════════════════════════
    Drill(
      id: 'cr_bowling',
      name: 'Fast Bowling Action',
      sport: 'Cricket',
      category: 'Bowling',
      description: 'Fast bowling delivery focusing on front knee brace and arm action.',
      instructions: [
        'Take a short run-up (5-7 steps)',
        'Leap into your bound (penultimate stride)',
        'Brace your front knee on landing',
        'Drive your bowling arm over with a high arm action',
      ],
      estimatedDuration: Duration(seconds: 12),
      difficulty: 'advanced',
      icon: '🏏',
      cameraPosition: 'side',
      scoringCriteria: [
        ScoringCriterion(
          name: 'Front Knee Brace',
          description: 'Front leg extension at delivery (braced = better pace)',
          weight: 0.30,
          metricType: 'angle',
          idealMin: 160, // Near-full extension for pace
          idealMax: 180,
          sigma: 10,
          landmarkA: 'leftHip',
          landmarkB: 'leftKnee',
          landmarkC: 'leftAnkle',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Arm Extension',
          description: 'Bowling arm should be near-straight at release',
          weight: 0.30,
          metricType: 'angle',
          idealMin: 165, // ICC allows up to 15° flexion
          idealMax: 180,
          sigma: 8,
          landmarkA: 'rightShoulder',
          landmarkB: 'rightElbow',
          landmarkC: 'rightWrist',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Trunk Rotation',
          description: 'Shoulder-hip separation for power generation',
          weight: 0.25,
          metricType: 'angle',
          idealMin: 140,
          idealMax: 170,
          sigma: 12,
          landmarkA: 'leftShoulder',
          landmarkB: 'leftHip',
          landmarkC: 'leftKnee',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Follow Through',
          description: 'Complete arm and body follow-through',
          weight: 0.15,
          metricType: 'form',
        ),
      ],
    ),
    Drill(
      id: 'cr_drive',
      name: 'Cover Drive',
      sport: 'Cricket',
      category: 'Batting',
      description: 'Classical cover drive technique with proper weight transfer.',
      instructions: [
        'Take your batting stance at the crease',
        'Step forward with your front foot toward the ball',
        'Extend your arms through the drive',
        'Keep your head over the ball and follow through',
      ],
      estimatedDuration: Duration(seconds: 10),
      difficulty: 'intermediate',
      icon: '🏏',
      cameraPosition: 'front',
      scoringCriteria: [
        ScoringCriterion(
          name: 'Front Foot Stride',
          description: 'Front knee angle at contact (bent = good transfer)',
          weight: 0.25,
          metricType: 'angle',
          idealMin: 110,
          idealMax: 140,
          sigma: 12,
          landmarkA: 'leftHip',
          landmarkB: 'leftKnee',
          landmarkC: 'leftAnkle',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Elbow Position',
          description: 'Front elbow should lead the stroke',
          weight: 0.30,
          metricType: 'angle',
          idealMin: 150, // Extended but not locked
          idealMax: 175,
          sigma: 10,
          landmarkA: 'leftShoulder',
          landmarkB: 'leftElbow',
          landmarkC: 'leftWrist',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Head Position',
          description: 'Head steady and over the ball',
          weight: 0.25,
          metricType: 'form',
        ),
        ScoringCriterion(
          name: 'Shoulder Rotation',
          description: 'Shoulders open through the drive',
          weight: 0.20,
          metricType: 'angle',
          idealMin: 130,
          idealMax: 160,
          sigma: 15,
          landmarkA: 'rightShoulder',
          landmarkB: 'leftShoulder',
          landmarkC: 'leftElbow',
          side: 'left',
        ),
      ],
    ),
    Drill(
      id: 'cr_throw',
      name: 'Fielding Throw',
      sport: 'Cricket',
      category: 'Fielding',
      description: 'Accurate overarm throw with proper shoulder rotation.',
      instructions: [
        'Pick up the ball on the move',
        'Align your body sideways to the target',
        'Rotate your trunk and extend your throwing arm',
        'Follow through toward the target',
      ],
      estimatedDuration: Duration(seconds: 10),
      difficulty: 'intermediate',
      icon: '🏏',
      cameraPosition: 'side',
      scoringCriteria: [
        ScoringCriterion(
          name: 'Shoulder Rotation',
          description: 'Trunk rotation for throw power',
          weight: 0.30,
          metricType: 'angle',
          idealMin: 140,
          idealMax: 170,
          sigma: 12,
          landmarkA: 'leftShoulder',
          landmarkB: 'leftHip',
          landmarkC: 'leftKnee',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Arm Extension',
          description: 'Throwing arm should reach full extension',
          weight: 0.30,
          metricType: 'angle',
          idealMin: 160,
          idealMax: 180,
          sigma: 10,
          landmarkA: 'rightShoulder',
          landmarkB: 'rightElbow',
          landmarkC: 'rightWrist',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Front Knee',
          description: 'Plant leg stable during throw',
          weight: 0.20,
          metricType: 'angle',
          idealMin: 155,
          idealMax: 175,
          sigma: 10,
          landmarkA: 'leftHip',
          landmarkB: 'leftKnee',
          landmarkC: 'leftAnkle',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Follow Through',
          description: 'Complete follow-through toward target',
          weight: 0.20,
          metricType: 'form',
        ),
      ],
    ),

    // ═══════════════════════════════════════════════════════════════
    //  ATHLETICS
    // ═══════════════════════════════════════════════════════════════
    Drill(
      id: 'ath_sprint',
      name: '100m Sprint Form',
      sport: 'Athletics',
      category: 'Speed',
      description: 'Sprint technique: drive phase, knee lift, and arm mechanics.',
      instructions: [
        'Start from a crouched position or blocks',
        'Drive out with powerful knee lifts',
        'Transition to upright sprinting form',
        'Maintain form through the finish line',
      ],
      estimatedDuration: Duration(seconds: 20),
      difficulty: 'advanced',
      icon: '🏅',
      cameraPosition: 'side',
      scoringCriteria: [
        ScoringCriterion(
          name: 'Drive Phase',
          description: 'Forward lean during initial acceleration',
          weight: 0.25,
          metricType: 'angle',
          idealMin: 140,  // Forward lean from knee-hip-shoulder
          idealMax: 165,
          sigma: 10,
          landmarkA: 'leftKnee',
          landmarkB: 'leftHip',
          landmarkC: 'leftShoulder',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Knee Lift',
          description: 'Peak knee height during stride',
          weight: 0.25,
          metricType: 'angle',
          idealMin: 65,   // Hip-knee-ankle at peak lift
          idealMax: 95,
          sigma: 12,
          landmarkA: 'leftHip',
          landmarkB: 'leftKnee',
          landmarkC: 'leftAnkle',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Arm Mechanics',
          description: 'Elbow drive and opposite arm-leg coordination',
          weight: 0.25,
          metricType: 'form',
          idealMin: 55,   // Elbow angle during arm swing
          idealMax: 95,
          sigma: 15,
          landmarkA: 'leftShoulder',
          landmarkB: 'leftElbow',
          landmarkC: 'leftWrist',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Stride Consistency',
          description: 'Uniform stride length throughout',
          weight: 0.25,
          metricType: 'consistency',
          landmarkA: 'leftHip',
          landmarkB: 'leftKnee',
          landmarkC: 'leftAnkle',
          side: 'auto',
        ),
      ],
    ),
    Drill(
      id: 'ath_javelin',
      name: 'Javelin Throw',
      sport: 'Athletics',
      category: 'Throws',
      description: 'Javelin throw technique: run-up, crossover, and release.',
      instructions: [
        'Start with a controlled run-up',
        'Perform crossover steps to align your body',
        'Drive from your back leg, rotate your trunk',
        'Release at the highest point with full arm extension',
      ],
      estimatedDuration: Duration(seconds: 12),
      difficulty: 'advanced',
      icon: '🏹',
      cameraPosition: 'side',
      scoringCriteria: [
        ScoringCriterion(
          name: 'Throwing Arm Extension',
          description: 'Full arm extension at release point',
          weight: 0.30,
          metricType: 'angle',
          idealMin: 160,  // Near-full extension
          idealMax: 180,
          sigma: 10,
          landmarkA: 'rightShoulder',
          landmarkB: 'rightElbow',
          landmarkC: 'rightWrist',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Trunk Rotation',
          description: 'Hip-shoulder separation angle',
          weight: 0.25,
          metricType: 'angle',
          idealMin: 140,
          idealMax: 170,
          sigma: 12,
          landmarkA: 'rightShoulder',
          landmarkB: 'rightHip',
          landmarkC: 'rightKnee',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Front Knee Brace',
          description: 'Block leg extends to transfer momentum',
          weight: 0.25,
          metricType: 'angle',
          idealMin: 155,
          idealMax: 180,
          sigma: 10,
          landmarkA: 'leftHip',
          landmarkB: 'leftKnee',
          landmarkC: 'leftAnkle',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Release Form',
          description: 'Body position and balance at release',
          weight: 0.20,
          metricType: 'form',
        ),
      ],
    ),
    Drill(
      id: 'ath_long_jump',
      name: 'Standing Long Jump',
      sport: 'Athletics',
      category: 'Jumps',
      description: 'Explosive standing long jump with proper takeoff and landing.',
      instructions: [
        'Stand with feet shoulder-width apart at the line',
        'Bend your knees and swing your arms behind you',
        'Explode forward, driving arms and extending legs',
        'Land with both feet and absorb the landing',
      ],
      estimatedDuration: Duration(seconds: 10),
      difficulty: 'beginner',
      icon: '🦘',
      cameraPosition: 'side',
      scoringCriteria: [
        ScoringCriterion(
          name: 'Takeoff Angle',
          description: 'Body angle at moment of takeoff',
          weight: 0.30,
          metricType: 'angle',
          idealMin: 130,  // Hip angle (not too upright, not too flat)
          idealMax: 155,
          sigma: 12,
          landmarkA: 'leftShoulder',
          landmarkB: 'leftHip',
          landmarkC: 'leftAnkle',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Arm Drive',
          description: 'Forward arm swing during takeoff',
          weight: 0.25,
          metricType: 'angle',
          idealMin: 130,  // Arms swing forward and up
          idealMax: 170,
          sigma: 15,
          landmarkA: 'leftShoulder',
          landmarkB: 'leftElbow',
          landmarkC: 'leftWrist',
          side: 'both',
        ),
        ScoringCriterion(
          name: 'Knee Extension',
          description: 'Full leg extension at takeoff',
          weight: 0.25,
          metricType: 'angle',
          idealMin: 155,
          idealMax: 180,
          sigma: 10,
          landmarkA: 'leftHip',
          landmarkB: 'leftKnee',
          landmarkC: 'leftAnkle',
          side: 'auto',
        ),
        ScoringCriterion(
          name: 'Landing Balance',
          description: 'Stable two-foot landing',
          weight: 0.20,
          metricType: 'form',
        ),
      ],
    ),
  ];

  /// Get active drills by sport.
  static List<Drill> getDrillsBySport(String sport) {
    return allDrills.where((d) => d.sport == sport && d.status == 'active').toList();
  }

  /// Get a single drill by ID.
  static Drill? getDrillById(String id) {
    try {
      return allDrills.firstWhere((d) => d.id == id);
    } catch (_) {
      return null;
    }
  }

  /// Check if a sport is coming soon.
  static bool isComingSoon(String sport) => comingSoonSports.contains(sport);
}
